from django.contrib import admin
from models import *

admin.site.register(Estado)
admin.site.register(OrdenDeCompra)
admin.site.register(Despacho)
admin.site.register(Usuario)
admin.site.register(Rol)
admin.site.register(TipoProducto)
admin.site.register(GrosorMaterial)
admin.site.register(Dimension)
admin.site.register(Kilogramos)
admin.site.register(Producto)
admin.site.register(TerminacionProducto)
admin.site.register(Terminacion)
admin.site.register(Dimensiones)
admin.site.register(OrdenTrabajo)
admin.site.register(DetalleOT)
admin.site.register(Operador)
admin.site.register(PuestoTrabajo)
admin.site.register(Tarea)
admin.site.register(OrdenTrabajoInterna)
admin.site.register(Material)
admin.site.register(SemiElaborado)
admin.site.register(MateriaPrima)
admin.site.register(Composicion)
admin.site.register(OrdenTrabajoMaterial)
